### ISSUE TITLE
Recent bug introduced

### ISSUE THREAD

**Issue by bbuzzanga** [aria-tools/ARIA-tools#182]
**Describe the bug**
Hi everyone. I'm rerunning an old analysis (last run about a month ago), that now fails. If the bug isn't immediately obvious @sssangha  I can do some more detective work to track down which commit introduces it.

**To Reproduce**
2. Command used
`ariaTSsetup.py -f '/Volumes/BB_4TB/data/VLM/Sentinel1/track_004/StandardProducts/products/S1*.nc' -b '36.75 37.225 -76.655 -75.928' -w '/Volume
s/BB_4TB/data/VLM/Sentinel1/track_004/Results/SP-HR/IGS14' -d Download -m Download -at 500 --bperp -nt 4`

3. Error Output
```
***Time-series Preparation Function:***
Shapefile /Volumes/BB_4TB/data/VLM/Sentinel1/track_004/Results/SP-HR/IGS14/user_bbox.shp created for input user bounds.
Multi-core version
All (277) GUNW products meet spatial bbox criteria.
Group GUNW products into spatiotemporally continuous interferograms.
All (277) interferograms are spatially continuous.
Thread count specified for gdal multiprocessing = 4
Download/cropping DEM
Downloaded 3 arc-sec SRTM DEM here: /Volumes/BB_4TB/data/VLM/Sentinel1/track_004/Results/SP-HR/IGS14/DEM/SRTM_3arcsec.dem
***Downloading water mask... ***

Extracting unwrapped phase, coherence, and connected components for each interferogram pair
Generating: unwrappedPhase - [==================================================] 20190629_20190617  256s /     5s
Generating: coherence - [==================================================] 20190629_20190617   62s /     1s

Extracting single incidence angle, look angle and azimuth angle files valid over common interferometric grid
Generating: incidenceAngle - [==================================================] 20150825_20150310
Generating: lookAngle - [==================================================] 20150825_20150310
Generating: azimuthAngle - [==================================================] 20150825_20150310

Extracting perpendicular baseline grids for each interferogram pair
Extracting perpendicular baseline grids for each interferogram pair
Generating: bPerpendicular - [=>                       3%                       ] 20161006_20160409   32s /  1049sWARNING: bPerpendicular layer
 for IFG 20161006_20160409 has R² of 0.443432 and standard error of 0.001991849209074916, automated correction applied
Generating: bPerpendicular - [=>                       3%                       ] 20161006_20160702   37s /  1204sWARNING: bPerpendicular layer
 for IFG 20161006_20160702 has R² of 0.513949 and standard error of 3.750919822461664, automated correction applied
Generating: bPerpendicular - [==>                      6%                       ] 20161030_20161018   73s /  1156sWARNING: bPerpendicular layer
 for IFG 20161030_20161018 has R² of 0.595478 and standard error of 1.536137790817688, automated correction applied
Generating: bPerpendicular - [===>                     7%                       ] 20161111_20150825   83s /  1103sWARNING: bPerpendicular layer
 for IFG 20161111_20150825 has R² of 0.789278 and standard error of 0.0026949460101785352, automated correction applied
Generating: bPerpendicular - [====>                   10%                       ] 20161205_20150825  119s /  1078sWARNING: bPerpendicular layer
 for IFG 20161205_20150825 has R² of 0.207231 and standard error of 4.664020063968888, automated correction applied
Generating: bPerpendicular - [=====>                  13%                       ] 20161229_20150825  155s /  1043sWARNING: bPerpendicular layer
 for IFG 20161229_20150825 has R² of 0.038654 and standard error of 0.0025839805303849495, automated correction applied
Generating: bPerpendicular - [=======>                15%                       ] 20170122_20150310  187s /  1063sWARNING: bPerpendicular layer
 for IFG 20170122_20150310 has R² of 0.005741 and standard error of 0.0019036984038158504, automated correction applied
Traceback (most recent call last):
  File "/Users/bb/Miniconda3/envs/ARIA/bin/ariaTSsetup.py", line 15, in <module>
    main(inps)
  File "/Users/bb/Miniconda3/envs/ARIA/lib/python3.7/site-packages/ARIAtools/tsSetup.py", line 280, in main
    export_products(standardproduct_info.products[1], standardproduct_info.bbox_file, prods_TOTbbox, layers, dem=demfile, lat=Latitude, lon=Lon
gitude, mask=inps.mask, outDir=inps.workdir, outputFormat=inps.outputFormat, stitchMethodType='overlap', verbose=inps.verbose, num_threads=inps
.num_threads, multilooking=inps.multilooking)
  File "/Users/bb/Miniconda3/envs/ARIA/lib/python3.7/site-packages/ARIAtools/extractProduct.py", line 324, in export_products
    finalize_metadata(outname, bounds, dem_bounds, prods_TOTbbox, dem, lat, lon, mask, outputFormat, verbose=verbose)
  File "/Users/bb/Miniconda3/envs/ARIA/lib/python3.7/site-packages/ARIAtools/extractProduct.py", line 582, in finalize_metadata
    data_array = metadata_qualitycheck(data_array, os.path.basename(os.path.dirname(outname)), outname, verbose).data_array
  File "/Users/bb/Miniconda3/envs/ARIA/lib/python3.7/site-packages/ARIAtools/extractProduct.py", line 393, in __init__
    self.__run__()
  File "/Users/bb/Miniconda3/envs/ARIA/lib/python3.7/site-packages/ARIAtools/extractProduct.py", line 555, in __run__
    rsquaredarr_rng, std_errarr_rng = self.__getCovar__('range', profprefix='corrected')
  File "/Users/bb/Miniconda3/envs/ARIA/lib/python3.7/site-packages/ARIAtools/extractProduct.py", line 457, in __getCovar__
    if (min(rsquaredarr) < 0.9 and max(std_errarr) > 0.01) or (i[0]==(len(eval('self.data_array_band%s'%(arrT)))-1)):
ValueError: min() arg is an empty sequence
```

**Comment by dbekaert** [comment]
@sssangha Can you move the print statement on the correction:
- under the verbose option?
- limit the number of decimal digits.
- add a unit to it.

**Comment by sssangha** [comment]
@dbekaert Ok I limited the decimal digits and passed the units, however shouldn't such warnings always be printed for transparency? This seems to be the convention for our code (e.g. see line 773 of ```extractProduct.py```). What do you think?

**Comment by dbekaert** [comment]
@sssangha we should migrate to a proper logging function for being better suitable for integration into SDS like systems, but we can do that separate.

**Comment by dbekaert** [comment]
@bbuzz31 this should be addressed in the new PR

**Comment by bbuzzanga** [comment]
Fixed with https://github.com/aria-tools/ARIA-tools/pull/181
