### ISSUE TITLE
AriaDownload, index out of range

### ISSUE THREAD

**Issue by nabolfat** [aria-tools/ARIA-tools#226]
When downloading a track using the follwoing command it gives the following error:
Command:
ariaDownload.py -b '35.3 36.3 -118.1 -117.2' -s 20190601 -e 20190820 -v -t 64 -w {data_dir}  -o download

Error:
Using  1 threads for parallel downloads
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/abolfath/opt/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/abolfath/opt/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/abolfath/opt/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/abolfath/opt/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/abolfath/opt/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/abolfath/opt/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 95, in _run_module_code
    with _TempModule(mod_name) as temp_module, _ModifiedArgv0(fname):
  File "/Users/abolfath/opt/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 56, in __enter__
    self._saved_value = sys.argv[0]
IndexError: list index out of range

 - ARIA-tools git tag: https://github.com/aria-tools/ARIA-tools.git
 - OS: Catalina, also tried on Mojave and did not work.

**Comment by dbekaert** [comment]
@bbuzz31 could you have a look, looks to be related to the concurrent download option?

**Comment by ehavazli** [comment]
@nabolfat @rzinke 
I am currently able to run the command without any issues and downloading the data.
Could you please confirm
```
-w {data_dir}
```
is correct?

Can you try to give the folder manually?

**Comment by EJFielding** [comment]
This works for me under Mojave. I use tcsh.
`ariaDownload.py -b '35.3 36.3 -118.1 -117.2' -s 20190601 -e 20190820 -v -t 64 -w coseis -o download`

**Comment by rzinke** [comment]
Hmm, this gives me the same error Niloufar mentioned.

**Comment by rzinke** [comment]
I am using Mojave, bash

**Comment by dbekaert** [comment]
Works for me as well. downloading all products now.

**Comment by EJFielding** [comment]
I can't tell if it is using the parallel download option.

**Comment by bbuzzanga** [comment]
@rzinke @nabolfat.

@ehavazli likely diagnosed the problem: assuming `{datadir}` is a variable you will need to expand it with a leading `$`.

**Comment by bbuzzanga** [comment]
> I can't tell if it is using the parallel download option.

@EJFielding if you are on the `dev` version there should be a line in the log (and also stdout if you didn't pipe it elsewhere) that lets you know the number of threads you're specified for downloading (default=1). Specifically, the log will have a line: Using  "N" threads for parallel downloads.

**Comment by EJFielding** [comment]
Sorry, I had not correctly installed the new `dev` version. Now when I run the same command it fails.
```
ariaDownload.py -b '35.3 36.3 -118.1 -117.2' -s 20190601 -e 201
https://api.daac.asf.alaska.edu/services/search/param?asfplatform=Sentinel-1%20Interferogram%20(BETA)&processingLevel=GUNW_STD&output=JSON&relativeOrbit=64&bbox=-118.1,35.3,-117.2,36.3
Found: S1-GUNW-A-R-064-tops-20190815_20190728-015015-36885N_35006N-PP-79de-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190815_20190803-015015-36885N_35006N-PP-90e0-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190815_20190809-015015-36885N_35006N-PP-9311-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190815_20190728-014950-35392N_33511N-PP-2c60-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190815_20190803-014950-35392N_33511N-PP-e27f-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190815_20190809-014950-35392N_33511N-PP-da6a-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190809_20190722-015105-37377N_35505N-PP-d801-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190809_20190728-015105-37377N_35505N-PP-65c2-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190809_20190803-015105-37377N_35505N-PP-9326-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190809_20190722-015039-35885N_33845N-PP-5255-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190809_20190728-015039-35885N_33845N-PP-534b-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190809_20190803-015039-35885N_33845N-PP-4e65-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190803_20190716-015014-36885N_35006N-PP-e1a8-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190803_20190722-015014-36885N_35006N-PP-9429-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190803_20190728-015014-36885N_35006N-PP-df05-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190803_20190716-014949-35392N_33511N-PP-a220-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190803_20190722-014949-35392N_33511N-PP-0dd9-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190803_20190728-014949-35392N_33511N-PP-5ee3-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190728_20190710-015104-37378N_35505N-PP-3ef3-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190728_20190716-015104-37378N_35505N-PP-ba8c-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190728_20190722-015104-37378N_35505N-PP-b755-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190728_20190710-015038-35886N_33845N-PP-8906-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190728_20190716-015038-35886N_33845N-PP-9ab6-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190728_20190722-015038-35886N_33845N-PP-a727-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190722_20190704-015013-36885N_35006N-PP-8fd1-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190722_20190710-015013-36885N_35006N-PP-9693-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190722_20190716-015013-36885N_35006N-PP-8939-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190722_20190704-014948-35392N_33511N-PP-ac9e-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190722_20190710-014948-35392N_33511N-PP-d8ea-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190722_20190716-014948-35392N_33511N-PP-d81c-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190716_20190628-015103-37378N_35505N-PP-8db4-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190716_20190704-015103-37378N_35505N-PP-f3e0-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190716_20190710-015103-37378N_35505N-PP-661a-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190716_20190628-015038-35886N_33845N-PP-bb31-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190716_20190704-015038-35886N_33845N-PP-c560-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190716_20190710-015038-35886N_33845N-PP-cf32-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190710_20190622-015013-36885N_35006N-PP-4110-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190710_20190628-015013-36885N_35006N-PP-a1b9-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190710_20190704-015013-36885N_35006N-PP-6e22-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190710_20190622-014948-35392N_33511N-PP-fd3e-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190710_20190628-014948-35392N_33511N-PP-eac2-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190710_20190704-014948-35392N_33511N-PP-548f-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190704_20190622-015102-37378N_35505N-PP-a9b2-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190704_20190628-015102-37378N_35505N-PP-b7dc-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190704_20190622-015037-35886N_33845N-PP-cf86-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190704_20190628-015037-35886N_33845N-PP-7e66-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190628_20190622-015012-36885N_35006N-PP-e715-v2_0_2
Found: S1-GUNW-A-R-064-tops-20190628_20190622-014947-35393N_33512N-PP-4e3b-v2_0_2
Attempting to obtaining user/pass from .netrc
 > attempting to download https://urs.earthdata.nasa.gov/profile
 > Re-using previous cookie jar.
Using  1 threads for parallel downloads
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 95, in _run_module_code
    with _TempModule(mod_name) as temp_module, _ModifiedArgv0(fname):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 56, in __enter__
    self._saved_value = sys.argv[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 95, in _run_module_code
    with _TempModule(mod_name) as temp_module, _ModifiedArgv0(fname):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 56, in __enter__
    self._saved_value = sys.argv[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 95, in _run_module_code
    with _TempModule(mod_name) as temp_module, _ModifiedArgv0(fname):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 56, in __enter__
    self._saved_value = sys.argv[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 95, in _run_module_code
    with _TempModule(mod_name) as temp_module, _ModifiedArgv0(fname):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 56, in __enter__
    self._saved_value = sys.argv[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 95, in _run_module_code
    with _TempModule(mod_name) as temp_module, _ModifiedArgv0(fname):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/runpy.py", line 56, in __enter__
    self._saved_value = sys.argv[0]
IndexError: list index out of range
...
```

**Comment by dbekaert** [comment]
Hi Eric,

I pulled a clean version from the dev branch
I tried your command, but cannot replicate.
Brett, can you replicate?

```
ariaDownload.py -b '35.3 36.3 -118.1 -117.2' -s 20190601 -e 20190820 -v -t
64 -w coseis -o download
https://api.daac.asf.alaska.edu/services/search/param?asfplatform=Sentinel-1%20Interferogram%20(BETA)&processingLevel=GUNW_STD&output=JSON&relativeOrbit=64&bbox=-118.1,35.3,-117.2,36.3


Found:
S1-GUNW-A-R-064-tops-20190628_20190622-015012-36885N_35006N-PP-e715-v2_0_2
Found:
S1-GUNW-A-R-064-tops-20190628_20190622-014947-35393N_33512N-PP-4e3b-v2_0_2
Attempting to obtaining user/pass from .netrc
 > attempting to download https://urs.earthdata.nasa.gov/profile
 > Re-using previous cookie jar.
Using  1 threads for parallel downloads
 > attempting to download https://urs.earthdata.nasa.gov/profile
 > Re-using previous cookie jar.
 > 'Temporary' Redirect download @ Remote archive:
 >
https://dlz0dhr6g6ukw.cloudfront.net/S1-GUNW-A-R-064-tops-20190815_20190728-015015-36885N_35006N-PP-79de-v2_0_2.nc?userid=dbekaert&Expires=1600292794&Signature=4MDAVwNyu33ud9lT1jOtVFooZL0~~tbMP343ztucasaVfp~6ZhT4eTM8peNfYPT~SIYcHo9akKLgTM1NJkCVuYysGb-0Q8cMwIn8rb1zaXonuuWYgenSPzbR2~sWFpq5tkCEy3w4zxS5ApTIgXwUjNTSzi3oUl3Zvmah8Fre-jA_&Key-Pair-Id=APKAINVNJF4BDB5SS5QQ
(1/48) Downloading
https://grfn.asf.alaska.edu/door/download/S1-GUNW-A-R-064-tops-20190815_20190728-015015-36885N_35006N-PP-79de-v2_0_2.nc
 > Downloaded 7626752 of 61983573 bytes (12.30%
```

**Comment by EJFielding** [comment]
To get a clean copy, do I need to only `git clone` and install ARIA-tools in a new directory, or do I need to make a whole new conda environment? It is possible that doing an update with `git pull` and then `python setup.py install` does not check all the requirements are met.

**Comment by nabolfat** [comment]
I tried again but I am getting the exact error as Eric.

**Comment by bbuzzanga** [comment]
Very strange. I'm not getting the error, products are downloading fine for me.

**Comment by ehavazli** [comment]
Hi @EJFielding you don't need to re-create a conda environment. A fresh git clone and then installation would work.

can you confirm you are pulling from the main dev branch and not your fork? Also which version of python are you using?

Can you try:
```
git pull upstream dev
```
if successful, then
```
git push --force
```

@rzinke and @nabolfat  could you also check which python version you are using?

**Comment by bbuzzanga** [comment]
thanks @ehavazli. A couple follow up suggestions to try: remove the `~.bulk_download_cookiejar.txt` to force a new cookie for ASF. Also perhaps update the packages in your conda environment.

**Comment by rzinke** [comment]
Python version 3.8.5.
I'm not sure exactly how setup.py works, but I usually install updates through that. What I did to get this error was I completely removed my old clone of ARIA-tools and removed the python environment. I then cloned directly from the main AT fork (not my personal one) and followed the instructions on the GitHub page for conda installation. My version from just two weeks ago did not produce an error.

**Comment by EJFielding** [comment]
I have my `origin` set to the `aria-tools` repository. I checked that I have the latest `dev`. I ran `conda update` and I deleted the `~/.bulk_download_cookiejar.txt` file. I still get the same error.

**Comment by bbuzzanga** [comment]
With the fresh install of ARIA-tools I'm also now getting this error argh

**Comment by bbuzzanga** [comment]
Okay, I've fixed the issue with https://github.com/aria-tools/ARIA-tools/pull/227. I'm not entirely sure where the problem originated from except that it is outside ariaTools. We're clearing the `os.sys.argv` variable which hold the arguments the user inputs in order to prevent spurious messages from the ASF download script. Python's multiprocessing library no longer can deal with this. Please let me know if you have further issues.

**Comment by EJFielding** [comment]
The download works again for me after the #227 fix.

**Comment by nabolfat** [comment]
Working for me as well after the #227 fix! Thanks!
