### ISSUE TITLE
[BUG] ERROR: Products do not overlap or were not provided in a contigious sorted list.

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#233]
**Bug**
I am processing a timeseries for track 19.
I pruned and checked the data using the ```ariaPlot.py``` function, cropping to intersection.

![lat_extents](https://user-images.githubusercontent.com/48299159/95297097-c0bc0f00-082e-11eb-8334-f95be49f5249.png)

When I apply the ```ariaTSsetup.py``` function, it runs for a while and then produces this error message.

```
NETCDF:"/u/sar-r2/rzinke/Tibet/T19_FullTrack_aria/19_S_Tibet/Sproducts/S1-GUNW-D-R-019-tops-20160517_20150405-001820-32430N_30444N-PP-ee95-v2_0_2.nc":/science/grids/data/connectedComponents is GDAL compatible
NETCDF:"/u/sar-r2/rzinke/Tibet/T19_FullTrack_aria/19_S_Tibet/Sproducts/S1-GUNW-D-R-019-tops-20160517_20150405-001845-30936N_28946N-PP-703d-v2_0_2.nc":/science/grids/data/unwrappedPhase is GDAL compatible
NETCDF:"/u/sar-r2/rzinke/Tibet/T19_FullTrack_aria/19_S_Tibet/Sproducts/S1-GUNW-D-R-019-tops-20160517_20150405-001845-30936N_28946N-PP-703d-v2_0_2.nc":/science/grids/data/connectedComponents is GDAL compatible
ERROR: Products do not overlap or were not provided in a contigious sorted list.
Traceback (most recent call last):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/aria/bin/ariaTSsetup.py", line 15, in <module>
    main(inps)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/aria/lib/python3.8/site-packages/ARIAtools/tsSetup.py", line 271, in main
    export_products(standardproduct_info.products[1], standardproduct_info.bbox_file, prods_TOTbbox, layers, dem=demfile, lat=Latitude, lon=Longitude, mask=inps.mask, outDir=inps.workdir, outputFormat=inps.outputFormat, stitchMethodType='overlap', verbose=inps.verbose, num_threads=inps.num_threads, multilooking=inps.multilooking)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/aria/lib/python3.8/site-packages/ARIAtools/extractProduct.py", line 380, in export_products
    product_stitch_overlap(unw_files,conn_files,prod_bbox_files,bounds,prods_TOTbbox, outFileUnw=outFileUnw,outFileConnComp= outFileConnComp, mask=mask,outputFormat = outputFormat,verbose=verbose)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/aria/lib/python3.8/site-packages/ARIAtools/unwrapStitching.py", line 1458, in product_stitch_overlap
    unw.UnwrapOverlap()
  File "/u/sar-r0/rzinke/python/miniconda3/envs/aria/lib/python3.8/site-packages/ARIAtools/unwrapStitching.py", line 340, in UnwrapOverlap
    self.__calculateCyclesOverlap__()
  File "/u/sar-r0/rzinke/python/miniconda3/envs/aria/lib/python3.8/site-packages/ARIAtools/unwrapStitching.py", line 369, in __calculateCyclesOverlap__
    raise Exception
Exception
```

**To Reproduce**
1.  ```ariaDownload.py -t 19 -i 20160517_20150405``` download products
2. ```ariaPlot.py -f "products/*.nc" -plottracks``` plot to confirm
3. ```ariaExtract.py -f "products/*.nc -ml 3 -w ML3" extract quickly```
4. ...```ERROR: Products do not overlap or were not provided in a contigious sorted list.```...

**Desktop (please complete the following information):**
 - ARIA-tools git tag: b787e82
 - Linux CentOS

**Comment by dbekaert** [comment]
via @sssangha fix in #235
