### ISSUE TITLE
Error -2 while decompressing data: inconsistent stream state

### ISSUE THREAD

**Issue by totaibi01** [aria-tools/ARIA-tools#250]
Hello ARIA team,

I'm working on the track 116 where I got the following error description:

Command used:
`ariaTSsetup.py -f 'products/*.nc' --mask Download -b "12 32 38 45" -d Download -mo 500000 -ml 5`

Error:
```
Traceback (most recent call last):
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/urllib3/response.py", line 400, in _decode
    data = self._decoder.decompress(data)
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/urllib3/response.py", line 86, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -2 while decompressing data: inconsistent stream state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/urllib3/response.py", line 769, in read_chunked
    chunk, decode_content=decode_content, flush_decoder=False
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/urllib3/response.py", line 406, in _decode
    e,
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -2 while decompressing data: inconsistent stream state',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thamer/miniconda3/bin/ariaTSsetup.py", line 15, in <module>
    main(inps)
  File "/home/thamer/ARIA-tools/tools/ARIAtools/tsSetup.py", line 270, in main
    prods_TOTbbox_metadatalyr, proj, arrshape=arrshape, workdir=inps.workdir, outputFormat=inps.outputFormat, num_threads=inps.num_threads)
  File "/home/thamer/ARIA-tools/tools/ARIAtools/extractProduct.py", line 299, in prep_dem
    demfilename = dl_dem(aria_dem, prods_TOTbbox_metadatalyr, num_threads)
  File "/home/thamer/ARIA-tools/tools/ARIAtools/extractProduct.py", line 369, in dl_dem
    r         = requests.get(_world_dem.format(*WESN), allow_redirects=True)
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 683, in send
    r.content
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/thamer/miniconda3/lib/python3.6/site-packages/requests/models.py", line 756, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -2 while decompressing data: inconsistent stream state',))
```

This error occurred during the download/cropping stage of the DEM.

Do you have any suggestions?

Thanks,
Thamer

**Comment by bbuzzanga** [comment]
Can you post the logging output?

I believe this was addressed with PR https://github.com/aria-tools/ARIA-tools/pull/249.

**Comment by totaibi01** [comment]
Sure, please find it below:

```
[2021-01-12 20:44:01,850]              __run__:455   WARNING    650 out of 4142 GUNW products rejected for not meeting user's bbox spatial criteria
[2021-01-12 21:00:35,720]  __continuous_time__:358   WARNING    306 products rejected since they are duplicates
[2021-01-12 21:13:28,776]               dl_dem:351   WARNING    User-defined bounds 518346km² supersedes DEM maximum download area of 225000km², must download in chunks
[2021-01-12 21:59:13,091]              __run__:455   WARNING    650 out of 4142 GUNW products rejected for not meeting user's bbox spatial criteria
[2021-01-12 22:13:42,924]  __continuous_time__:358   WARNING    306 products rejected since they are duplicates
[2021-01-12 22:25:00,669]               dl_dem:351   WARNING    User-defined bounds 518354km² supersedes DEM maximum download area of 225000km², must download in chunks
```
I will double check the other resolved issue

**Comment by totaibi01** [comment]
I just resolved the problem. It was similar to the issue #249 

Thanks @bbuzz31 for following up
