### ISSUE TITLE
[BUG] Output url option not working

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#283]
**Describe the bug**
I am trying to process some data without downloading the standard products. I get two different errors when I try, however.

**To Reproduce**
1. Download
```
ariaDownload.py -o Url -t 42 -b /u/sar-r2/rzinke/Parkfield/Shapefiles/ParkfieldTestPatch.shp -w Dsc042 -nt 4 --verbose
```

2. Command used
```
ariaTSsetup.py -f Dsc042/download_products_42track_-122W35S-120E{WSEN_fmt[3]}Nbbox_0.txt -w Dsc042 -d download -m download -nt 8 --verbose
```

3. Interestingly, I get two errors:

First, when I try to run ```ariaTSsetup.py``` using a Linux screen, I get the following error:
```
Traceback (most recent call last):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/bin/ariaTSsetup.py", line 18, in <module>
    main(inps)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.9/site-packages/ARIAtools/tsSetup.py", line 396, in main
    standardproduct_info = ARIA_standardproduct(inps.imgfile,
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.9/site-packages/ARIAtools/ARIAProduct.py", line 104, in __init__
    fmt=gdal.Open([s for s in self.files if 'https://' in s][0]).GetDriver().GetDescription()
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.9/site-packages/osgeo/gdal.py", line 4473, in Open
    return _gdal.Open(*args)
RuntimeError: HTTP response code: 403
```

Second, when I try in the terminal directly, without a screen, I get:
```
Traceback (most recent call last):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/bin/ariaTSsetup.py", line 18, in <module>
    main(inps)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.9/site-packages/ARIAtools/tsSetup.py", line 396, in main
    standardproduct_info = ARIA_standardproduct(inps.imgfile,
  File "/u/sar-r0/rzinke/python/miniconda3/envs/ARIA-tools/lib/python3.9/site-packages/ARIAtools/ARIAProduct.py", line 105, in __init__
    if fmt != 'netCDF': raise Exception ('System update required to ' \
Exception: System update required to read requested virtual products: Linux kernel >=4.3 and libnetcdf >=4.5
```

**Expected behavior**
I would hope ```ariaTSsetup.py``` runs as it would if I had downloaded the .nc files directly.

**Desktop (please complete the following information):**
 - ARIA-tools git tag: 
commit bcb95152d5d5a13308e0c889283a1e8360db41c6 (HEAD -> dev, origin/dev, origin/HEAD)
Author: BB <bbuzz318@icloud.com>
Date:   Mon Aug 2 14:08:32 2021 -0700

 - OS
 CentOS Linux, version 7 (JPL sar machine)

**Comment by dbekaert** [comment]
Hi Rob,

This is not a bug of virtual processing not working.
Rather it seems that when executed in a screen the error message is
correctly propagated.

The second error message is correct and as indicated shows you are not
meeting the requirements to support virtual data processing.
Kernel requirements would be satisfied under OS centos 8, hence virtual
processing was developed on OSL not on JPL server.

**Comment by rzinke** [comment]
I see. So I'd have to use a more recent OS to use this option?

**Comment by dbekaert** [comment]
That is correct, your only current option using that system is to download
the data.

**Comment by rzinke** [comment]
Thanks for clarifying, @dbekaert
