### ISSUE TITLE
[BUG] ariaDownload 1.1 fails when files exist

### ISSUE THREAD

**Issue by EJFielding** [aria-tools/ARIA-tools#289]
**Describe the bug**
The old version of ariaDownload would ignore files that already exist. The ariaDownload 1.1.0 quits when it finds files that already exist.

**To Reproduce**
1. Download the standard SF ARIA tutorial data
2. Command used: `ariaDownload.py -b '37.25 38.1 -122.6 -121.75' --track 42`
3. Error Output:
The first time I ran the download it had three files with errors (I think exactly the same three failed on both my Mac and NISAR Linux server)
```
ARIA-tools Version: 1.1.0
Traceback (most recent call last):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/urllib3/response.py", line 518, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/requests/models.py", line 758, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/urllib3/response.py", line 575, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/urllib3/response.py", line 540, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/bin/ariaDownload.py", line 293, in <module>
    Downloader(inps)()
  File "/Users/fielding/anaconda3/envs/ARIA-tools/bin/ariaDownload.py", line 260, in __call__
    scenes.download(self.inps.wd, processes=nt)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/asf_search/ASFSearchResults.py", line 32, in download
    product.download(path=path, session=session)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/asf_search/ASFProduct.py", line 38, in download
    download_url(url=self.properties['url'], path=path, filename=filename, session=session)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/asf_search/download/download.py", line 77, in download_url
    for chunk in response.iter_content(chunk_size=8192):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/requests/models.py", line 761, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))
(ARIA-tools)
```
I tried running it again to see if it was a transient failure and it immediately complained about files already existing:
```
ARIA-tools Version: 1.1.0
Traceback (most recent call last):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/bin/ariaDownload.py", line 293, in <module>
    Downloader(inps)()
  File "/Users/fielding/anaconda3/envs/ARIA-tools/bin/ariaDownload.py", line 260, in __call__
    scenes.download(self.inps.wd, processes=nt)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/asf_search/ASFSearchResults.py", line 32, in download
    product.download(path=path, session=session)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/asf_search/ASFProduct.py", line 38, in download
    download_url(url=self.properties['url'], path=path, filename=filename, session=session)
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.8/site-packages/asf_search/download/download.py", line 61, in download_url
    raise ASFDownloadError(f'File already exists: {os.path.join(path, filename)}')
asf_search.exceptions.ASFDownloadError: File already exists: /Users/fielding/Downloads/SF_ARIA/products/S1-GUNW-D-R-042-tops-20210802_20210715-140737-38459N_36646N-PP-acf2-v2_0_4.nc
(ARIA-tools)
```

**Expected behavior**
I expected the second `ariaDownload` to either retry the files that failed or say the files were already downloaded.

**Screenshots**

**Desktop (please complete the following information):**
 - ARIA-tools git tag: [e.g. git show --summary] 
 ```
commit 0251a1dce5230378a2391e54467343e662fdfadf (HEAD -> dev, origin/dev, origin/HEAD)
Author: BB <bbuzz318@icloud.com>
Date:   Mon Nov 29 11:05:23 2021 -0800
```
 - OS: MacOS and Linux

**Additional context**

**Comment by bbuzzanga** [comment]
Hi @EJFielding. This is not an `ariaDownload` problem but an issue with asf_search. I also found it when I updated the `ariaDownload` wrapper a month or two back (https://github.com/asfadmin/Discovery-asf_search/issues/65). It's hacky to implement in the wrapper, so I'd rather have them more robustly handle it (to include partial downloads, etc) as they did in their previous bulk downloader. If you could give an upvote to the issue (https://github.com/asfadmin/Discovery-asf_search/issues/65) it might help things to move along a bit.

**Comment by EJFielding** [comment]
Thanks for the explanation. I added a comment of support for fixing this upstream.

**Comment by EJFielding** [comment]
It seems the upstream fix works now.
