### ISSUE TITLE
[BUG] "np.float" no longer available

### ISSUE THREAD

**Issue by EJFielding** [aria-tools/ARIA-tools#336]
**Describe the bug**
`ariaExtract.py` fails when it tries to show progress bar because it is using "np.float". The `numpy.float` alias was removed removed from numpy v 1.24 from what I found.

**To Reproduce**
1. Download 
2. `ariaExtract.py -f products/S1-GUNW-D-R-013-tops-20221223_20221211-142407-00126W_00039N-PP-2c4c-v2_0_6.nc --layers all`
3. Error Output:
```
ARIA-tools Version: 1.1.4
*****************************************************************
*** Extract Product Function ***
*****************************************************************
All (1) GUNW products meet spatial bbox criteria.
Group GUNW products into spatiotemporally  continuous interferograms.
All (1) interferograms are spatially continuous.
All layers are to be extracted, pass all keys.
Thread count specified for gdal multiprocessing = 2
/Users/fielding/tools/ARIA-tools/tools/ARIAtools/shapefile_util.py:70: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if file_bbox.type == 'Polygon': file_bbox = [file_bbox]
Traceback (most recent call last):
  File "/Users/fielding/anaconda3/envs/ARIA-tools/bin/ariaExtract.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/fielding/tools/ARIA-tools/tools/bin/ariaExtract.py", line 21, in <module>
    main(inps)
  File "/Users/fielding/tools/ARIA-tools/tools/ARIAtools/extractProduct.py", line 1205, in main
    export_products(standardproduct_info.products[1], standardproduct_info.bbox_file,
  File "/Users/fielding/tools/ARIA-tools/tools/ARIAtools/extractProduct.py", line 598, in export_products
    prog_bar = progBar.progressBar(maxValue=len(product_dict[0]),prefix='Generating: '+key+' - ')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fielding/tools/ARIA-tools/tools/ARIAtools/progBar.py", line 40, in __init__
    self.reset()
  File "/Users/fielding/tools/ARIA-tools/tools/ARIAtools/progBar.py", line 45, in reset
    self.update_amount(0)  # Build progress bar string
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fielding/tools/ARIA-tools/tools/ARIAtools/progBar.py", line 58, in update_amount
    diffFromMin = np.float(self.amount - self.min)
                  ^^^^^^^^
  File "/Users/fielding/anaconda3/envs/ARIA-tools/lib/python3.11/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?
```

**Expected behavior**
Should run.

**Screenshots**

**Desktop (please complete the following information):**
 - ARIA-tools git tag: [e.g. git show --summary]
```
commit 438e3e6a1853f688c8431d4c2a97ba181d09bed6 (HEAD -> dev, origin/dev, origin/HEAD)
Merge: 844fa0d cca281c
Author: BB <bbuzz318@icloud.com>
Date:   Tue Nov 29 09:04:12 2022 -0800

    Merge pull request #332 from aria-tools/sss_vestigevariable

    Remove vestigial assignment of sensing time
```
 - OS   macOS Anaconda environment

**Additional context**
`numpy                     1.24.1          py311h62c7003_0    conda-forge`

**Comment by sssangha** [comment]
@EJFielding , I've noted this deprecation and addressed it as a part of an active PR #335

Note the main additions to the code may not be of relevance to your immediate processing efforts, but I'd advise you work off of it for now as we work to some lagging patches before merging.

**Comment by EJFielding** [comment]
Thanks. Great to see you are already addressing this in the PR. For now, I can downgrade my `numpy` version to 1.23 that still allows the usage in the main branch version.

**Comment by dbekaert** [comment]
@sssangha Please close when considered merge and completed.
