### ISSUE TITLE
[BUG] aztime error

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#359]
**Describe the bug**
I am running `ariaTSsetup.py` to create a timeseries. Most of the products are computed, but an error is thrown before the final stack is generated. The error seems to indicate that an `aztime` cannot be found.

**To Reproduce**
1. Download 
```
ariaDownload.py -t 121 -b ../../AOIs/track_121_TibetB/track_121_TibetB.shp -s 20220101 -e 20221231
```

2. Command used
```
ariaTSsetup.py -f "products/*.nc" -w 9arc -b ../../AOIs/track_121_TibetB/track_121_TibetB.shp -d download -m download -nt 8 -mo 238000 -ml $looks -v
```

3. Error Output
```
...
NETCDF:"/data/Tibet/Track121/Timeseries/2022/products/S1-GUNW-D-R-121-tops-20220505_20220423-001148-00085E_00026N-PP-d008-v2_0_5.nc":/science/grids/data/unwrappedPhase is GDAL compatible
NETCDF:"/data/Tibet/Track121/Timeseries/2022/products/S1-GUNW-D-R-121-tops-20220505_20220423-001148-00085E_00026N-PP-d008-v2_0_5.nc":/science/grids/data/connectedComponents is GDAL compatible
NETCDF:"/data/Tibet/Track121/Timeseries/2022/products/S1-GUNW-D-R-121-tops-20220505_20220423-001213-00085E_00025N-PP-d2f3-v2_0_5.nc":/science/grids/data/unwrappedPhase is GDAL compatible
NETCDF:"/data/Tibet/Track121/Timeseries/2022/products/S1-GUNW-D-R-121-tops-20220505_20220423-001213-00085E_00025N-PP-d2f3-v2_0_5.nc":/science/grids/data/connectedComponents is GDAL compatible

Generating: coherence - [==================================================] 20220505_20220423  560s /    29s

Extracting single incidence angle, look angle and azimuth angle files valid over common interferometric grid
Generating: incidenceAngle - [==================================================] 20220117_20220105
Generating: lookAngle - [==================================================] 20220117_20220105
Generating: azimuthAngle - [==================================================] 20220117_20220105

Extracting perpendicular baseline grids for each interferogram pair
Generating: bPerpendicular - [==================================================] 20220505_20220423 1172s /    61s
All available tropo models are to be extracted
WARNING: User-requested tropo model HRES will not be generated as it does not exist in any of the input products
WARNING: User-requested tropo model ERA5 will not be generated as it does not exist in any of the input products
WARNING: User-requested tropo model GMAO will not be generated as it does not exist in any of the input products
WARNING: User-requested tropo model HRRR will not be generated as it does not exist in any of the input products
WARNING: User-requested computation of raider-derived total troposphere "-l troposphereTotal" is not possible as tropo component layers are not common to all products.
Creating directory:  9arc/stack
Number of unwrappedPhase files discovered:  150
Traceback (most recent call last):
  File "/home/rzinke/miniconda3/envs/ARIA-tools/bin/ariaTSsetup.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/rzinke/tools/ARIA-tools/tools/bin/ariaTSsetup.py", line 18, in <module>
    main(inps)
  File "/home/rzinke/tools/ARIA-tools/tools/ARIAtools/tsSetup.py", line 550, in main
    ref_dlist = generate_stack(standardproduct_info, 'unwrappedPhase',
  File "/home/rzinke/tools/ARIA-tools/tools/ARIAtools/tsSetup.py", line 294, in generate_stack
    utc_time = extract_utc_time(aria_dates, aztime_list)
  File "/home/rzinke/tools/ARIA-tools/tools/ARIAtools/tsSetup.py", line 198, in extract_utc_time
    mid_time_list = aztime_list[i]
IndexError: list index out of range
```

**Desktop:**
 - ARIA-tools git tag: commit 6e54101a42e5fd525097a1784fdf2ea800754812
 - OS Linux CentOS

**Comment by dbekaert** [comment]
@sssangha looks like a backward compatible issue? Have these products been generated with the 1c flag? Also looks weird that it tries to compute the tropo for all models. Some of the logic looks off.

**Comment by rzinke** [comment]
I am not sure about the 1c flag.

Note that they are all 2022 products.
Interestingly, I ran the same process for 2018 and 2020 products, and the stack was computed successfully.
... Although it appears there is still an issue in multi-looking the coherence maps, described in https://github.com/aria-tools/ARIA-tools/issues/352
