### ISSUE TITLE
[BUG]ionosphere temp file not found during dim check

### ISSUE THREAD

**Issue by rzinke** [aria-tools/ARIA-tools#447]
**Describe the bug**
`ariaTSsetup.py` is throwing an error when extracting ionosphere layers. It appears to be failing while checking for layers of a previous product that does not (or no longer) exists. The issue is possibly related to issue https://github.com/aria-tools/ARIA-tools/issues/420 and [PR 421](https://github.com/aria-tools/ARIA-tools/commit/b0f042a5c1e8f4eae76bc1bcd531df96c1507fdd).

**To Reproduce**
1. Download three products
```
ariaDownload.py -t 71 -b '37.5 39.5 -118.5 -114.5' -s 20200515 -e 20200601
```
2. Command used
```
ariaTSsetup.py -f "./products/*.nc" -l ionosphere
```
3. Error Output
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/insarX/bin/ariaTSsetup.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/rzinke/Tools/ARIA-tools/tools/bin/ariaTSsetup.py", line 669, in <module>
    main()
  File "/Users/rzinke/Tools/ARIA-tools/tools/bin/ariaTSsetup.py", line 600, in main
    prod_arr_record = ARIAtools.extractProduct.export_products(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rzinke/Tools/ARIA-tools/tools/ARIAtools/extractProduct.py", line 1338, in export_products
    ARIAtools.util.vrt.get_basic_attrs(prev_outname_check + '.vrt')
  File "/Users/rzinke/Tools/ARIA-tools/tools/ARIAtools/util/vrt.py", line 527, in get_basic_attrs
    data_set = osgeo.gdal.Open(fname)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/insarX/lib/python3.12/site-packages/osgeo/gdal.py", line 8817, in Open
    return _gdal.Open(*args)
           ^^^^^^^^^^^^^^^^^
RuntimeError: GDALWarpOptions.Validate(): hSrcDS is not set.
May be caused by: /Users/rzinke/Documents/ARIAdev/Corrections/MonteCristo/test/ionosphere/temp_20200529_20200523.vrt: No such file or directory
```

**Expected behavior**
Extraction of `stack/ionoStack.vrt` as demonstrated in the ARIA-tools-docs [notebook](https://github.com/aria-tools/ARIA-tools-docs/blob/master/JupyterDocs/ariaTSsetup/ariaTSsetup_tutorial.ipynb). I am not sure why it worked there but not in my case, as the notebook was updated more recently than PR 421. 

**Desktop (please complete the following information):**
 - ARIA-tools git tag: 7b151f926438a5f3eb6375f982d420096808eaf0
 - OS: macOS Sonoma 14.7

**Comment by rzinke** [comment]
GDAL looks for a temp_xxxx file on which cropped and resampled datasets are built, however, the temp files are deleted. Extracting to disk (for both multiple products and single product) fixes this issue.

Suggested fix in PR https://github.com/aria-tools/ARIA-tools/pull/448
